//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace WeatherDisplay.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue(@"metadata=res://*/WeatherModel.csdl|res://*/WeatherModel.ssdl|res://*/WeatherModel.msl;provider=System.Data.SqlClient;provider connection string=""data source=localhost;initial catalog=WeatherDisplay;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework""")]
        public string DataConnection {
            get {
                return ((string)(this["DataConnection"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("524901")]
        public ulong CityId {
            get {
                return ((ulong)(this["CityId"]));
            }
        }
    }
}
